FROM eclipse-temurin:17-jre

LABEL org.opencontainers.image.source="https://github.com/Digital-Maritime-Consultancy/MaritimeResourceRegistry"

COPY mrr-0.0.1-SNAPSHOT.jar .

ENTRYPOINT ["java", "-jar", "mrr-0.0.1-SNAPSHOT.jar"]
